### PR TITLE
Fix jnats for jruby >= 9.2.10.0

### PR DESCRIPTION
**Pull request by film42**
Newer jruby and jdk 9 does not bind private methods or non-interface methods. This uses a forked java-nats to keep this lib working with the old client until https://github.com/abrandoned/protobuf-nats/pull/42 is merged.

### CODE REVIEW

**Comment by film42** [comment]
Here are the relevant changes we made to java-nats: https://github.com/nats-io/nats.java/compare/master...film42:jruby-compat?expand=1

**Comment by skunkworker** [comment]
@film42 Looks good to me, let's cut a RC release first.

**Comment by film42** [comment]
Released pre-release: `0.10.3.pre0`.

**Comment by film42** [comment]
Running stable in production on the latest jruby. Releasing...

**Comment by film42** [comment]
Released as `v0.10.3`.

**Pull request merged**
