### PR TITLE
Send a NACK when the server is full

### PR DESCRIPTION
**Pull request by film42**
We're safe to roll this out now. 

Once this has a :shipit: I'm going to cut a pre and try it out before merging just to make sure we didn't miss anything.

cc @quixoten @abrandoned @mmmries

### CODE REVIEW

**Comment by film42** [comment]
Cut a pre: `0.7.0.pre1`.

**Comment by film42** [comment]
Testing the pre with one of our production services for a few days.

**Comment by film42** [comment]
Things are looking great but I am struggling to find a case where invoking a NACK improves performance over a timeout. Maybe I'm thinking about it wrong. Any ideas?

**Comment by quixoten** [comment]
What use cases have you tried so far? My initial thought is that it will be most effective during bursts of traffic that could potentially cause many 5 second delays across multiple clients when NACK is not present. With NACK present, that delay should be much shorter.

**Comment by film42** [comment]
Created a server with 1 thread.
Took the `real_client.rb` benchmark and ran it on 20 threads in the same process.

BEFORE (no NACK):
```
                          0.100  (± 0.0%) i/s -      1.000  in  10.002670s
    155.741  (±97.0%) i/s -      5.000  in  10.018034s
    743.773  (±36.3%) i/s -     65.000  in  10.113324s
    706.000  (±39.1%) i/s -    364.000  in  10.604879s
    510.171  (±30.4%) i/s -      1.956k in  14.375146s
      0.100  (± 0.0%) i/s -      1.000  in  10.002784s
      0.100  (± 0.0%) i/s -      1.000  in  10.005379s
    312.638  (±103.0%) i/s -      4.000  in  10.012684s    343.302  (±46.0%) i/s -     78.000  in  15.194623s

    941.000  (±29.9%) i/s -      4.004k in  14.954038s
    829.088  (±40.5%) i/s -      2.930k in  14.460520s
    667.544  (±34.0%) i/s -      3.003k in   9.965678s
    651.649  (±37.6%) i/s -    828.000  in  11.472175s
      0.067  (± 0.0%) i/s -      1.000  in  15.002810s
      0.067  (± 0.0%) i/s -      1.000  in  15.002642s
      0.100  (± 0.0%) i/s -      1.000  in  10.002774s
      0.150  (± 0.0%) i/s -      2.000  in  15.004709s
     67.701  (±100.4%) i/s -      2.000  in  15.010529s
    790.779  (±67.5%) i/s -      4.000  in  10.006746s
    585.661  (±90.8%) i/s -      5.000  in  15.010049s
REQUEST TIMEOUTS: 14
RESPONSE TIMEOUTS: 0
```

AFTER (with NACK):
```
                        436.156  (±94.9%) i/s -    932.000  in  10.004741s
    587.018  (±74.1%) i/s -      1.029k in  10.002143s
    418.483  (±96.5%) i/s -      1.012k in  10.018266s
    432.239  (±94.9%) i/s -    960.000  in  10.007814s    598.696  (±72.2%) i/s -      1.137k in   9.993591s

    570.840  (±74.3%) i/s -      1.003k in   9.995233s
    437.317  (±93.1%) i/s -      1.024k in  10.037479s
    563.051  (±75.5%) i/s -      1.058k in  10.009351s
    590.248  (±71.3%) i/s -      1.099k in   9.993322s
    464.568  (±90.8%) i/s -      1.068k in  10.017525s
    413.808  (±97.4%) i/s -    974.000  in  10.038259s
    574.515  (±71.9%) i/s -      1.055k in  10.026527s
    404.462  (±98.2%) i/s -      1.000k in  10.052760s
    426.861  (±98.6%) i/s -    928.000  in  10.028523s
    454.496  (±90.0%) i/s -      1.022k in  10.010082s
    595.255  (±71.2%) i/s -      1.067k in  10.057451s
    559.439  (±76.5%) i/s -    964.000  in   9.994276s
    444.458  (±90.2%) i/s -      1.018k in  10.051999s
    547.683  (±80.0%) i/s -    868.000  in  10.022633s
    450.211  (±90.8%) i/s -      1.066k in  10.080726s
REQUEST TIMEOUTS: 2363
RESPONSE TIMEOUTS: 0
```

Looks much better!!! ❤️

**Comment by film42** [comment]
Everything in prod looks good, and the benchmark above shows a real improvement, so this is now released as `0.7.0`.

**Pull request merged**
